// Minimal DTCG token builder: resolves aliases and emits CSS variables + a typed nested TS object.
// Source of truth = src/tokens/*.json (W3C DTCG draft: { "$type", "$value" }).
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(here, 'src', 'tokens');
const generatedPath = join(here, 'src', 'generated.ts');
const distDir = join(here, 'dist');
const cssPath = join(distDir, 'tokens.css');

const isObject = (v) => v && typeof v === 'object' && !Array.isArray(v);
const isLeaf = (node) => isObject(node) && '$value' in node;

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (isObject(source[key]) && isObject(target[key])) deepMerge(target[key], source[key]);
    else target[key] = source[key];
  }
  return target;
}

// Load + merge every token file.
const raw = {};
for (const file of readdirSync(tokensDir).filter((f) => f.endsWith('.json'))) {
  deepMerge(raw, JSON.parse(readFileSync(join(tokensDir, file), 'utf8')));
}

function getByPath(path) {
  return path.split('.').reduce((acc, key) => (acc ? acc[key] : undefined), raw);
}

// Resolve "{a.b.c}" alias strings anywhere in a value (string, array, or object field).
function resolve(value) {
  if (typeof value === 'string') {
    const match = value.match(/^\{(.+)\}$/);
    if (match) {
      const target = getByPath(match[1]);
      if (!isLeaf(target)) throw new Error(`Unresolved token alias: ${value}`);
      return resolve(target.$value);
    }
    return value;
  }
  if (Array.isArray(value)) return value.map(resolve);
  if (isObject(value)) {
    const out = {};
    for (const key of Object.keys(value)) out[key] = resolve(value[key]);
    return out;
  }
  return value;
}

function shadowToCss(shadow) {
  const list = Array.isArray(shadow) ? shadow : [shadow];
  return list
    .map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`.trim())
    .join(', ');
}

// Resolve a leaf to a code-friendly primitive (shadows become CSS box-shadow strings).
function resolveLeaf(node) {
  const value = resolve(node.$value);
  if (node.$type === 'shadow') return shadowToCss(value);
  return value;
}

// Build nested resolved object (for TS) + flat list (for CSS variables).
const cssVars = [];
function build(node, path) {
  if (isLeaf(node)) {
    const value = resolveLeaf(node);
    cssVars.push([path.join('-'), value]);
    return value;
  }
  const out = {};
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue;
    out[key] = build(node[key], [...path, key]);
  }
  return out;
}

const resolved = build(raw, []);

// Emit TS.
const tsBody = `// AUTO-GENERATED by build.mjs — do not edit.
export const tokens = ${JSON.stringify(resolved, null, 2)} as const;

export type Tokens = typeof tokens;
`;
writeFileSync(generatedPath, tsBody);

// Emit CSS custom properties.
const cssBody = `:root {\n${cssVars
  .map(([name, value]) => `  --${name}: ${value};`)
  .join('\n')}\n}\n`;
if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
writeFileSync(cssPath, cssBody);

console.log(`tokens: wrote ${cssVars.length} variables -> generated.ts + dist/tokens.css`);
